<?php
// Firebase API Key
define('API_ACCESS_KEY','AAAACfs-hIU:APA91bGSnpeSeTsRfAfaSYwUAPt7pDrKzWwbc2BrMwrHVoUDaAkG2P7wViJ3b-Gnl9CIUB4w2DTBflvFBzAJo4Y24VrR9Phy3rerSzK_y3IpENIjjm1zJGYdJsLi8LAShKgKvnmL6JX8');
define('WEB_API_KEY', 'AIzaSyB6R-KbRHpLh0YD5g1TmLV9sRIAQBuDdZ0');
